name       : lzip
version    : '1.20'
release    : 4
source     :
    - https://download.savannah.gnu.org/releases/lzip/lzip-1.20.tar.gz : c93b81a5a7788ef5812423d311345ba5d3bd4f5ebf1f693911e3a13553c1290c
license    : GPL-2.0-or-later
component  : system.base
summary    : Lossless data compressor
description: |
    Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2. Lzip is about as fast as gzip, compresses most files more than bzip2, and is better than both from a data recovery perspective. Lzip is a clean implementation of the LZMA "algorithm".
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
