name       : lzip
version    : 1.19
release    : 3
source     :
    - https://download.savannah.gnu.org/releases/lzip/lzip-1.19.tar.gz : ffadc4f56be1bc0d3ae155ec4527bd003133bdc703a753b2cc683f610e646ba9
license    : GPL-2.0
component  : system.base
summary    : Lossless data compressor
description: |
    Lzip is a lossless data compressor with a user interface similar to the one of gzip or bzip2. Lzip is about as fast as gzip, compresses most files more than bzip2, and is better than both from a data recovery perspective. Lzip is a clean implementation of the LZMA "algorithm".
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
